# add_extensive_training_data.py: إضافة بيانات تدريب شاملة جداً
"""
سكريبت لإضافة بيانات تدريب شاملة جداً للشات بوت
Script to add extensive training data for the chatbot
"""
import logging
import os
from database import save_scraped_data, save_medical_data, save_conversation, Session

os.makedirs('logs', exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/extensive_training.log', encoding='utf-8'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# بيانات تدريب شاملة جداً - 100+ محادثة
EXTENSIVE_CONVERSATIONS = [
    # ========== تحيات متنوعة ==========
    {'user_id': 'ext-1', 'message': 'السلام عليكم', 'response': 'وعليكم السلام ورحمة الله وبركاته! 🌟 أهلاً وسهلاً بك في مساعد إيفا الذكي. كيف يمكنني مساعدتك اليوم؟', 'intent': 'greeting', 'sentiment': 'positive', 'confidence': 0.95},
    {'user_id': 'ext-2', 'message': 'صباح الخير', 'response': 'صباح النور! ☀️ أهلاً بك في مساعد إيفا. كيف يمكنني مساعدتك في العناية ببشرتك أو شعرك اليوم؟', 'intent': 'greeting', 'sentiment': 'positive', 'confidence': 0.95},
    {'user_id': 'ext-3', 'message': 'مساء الخير', 'response': 'مساء النور! 🌙 أهلاً بك. أنا هنا لأساعدك في أي استفسار عن منتجات إيفا أو العناية بالبشرة والشعر.', 'intent': 'greeting', 'sentiment': 'positive', 'confidence': 0.95},
    {'user_id': 'ext-4', 'message': 'Good morning', 'response': 'Good morning! ☀️ Welcome to Eva\'s smart assistant. How can I help you with skincare or haircare today?', 'intent': 'greeting', 'sentiment': 'positive', 'confidence': 0.95},
    {'user_id': 'ext-5', 'message': 'Hello there', 'response': 'Hello! 👋 I\'m Eva\'s smart assistant, ready to help you with beauty and care questions. What would you like to know?', 'intent': 'greeting', 'sentiment': 'positive', 'confidence': 0.95},
    
    # ========== أسئلة عن الشركة ==========
    {'user_id': 'ext-6', 'message': 'إيه قصة إيفا؟', 'response': 'إيفا كوزمتكس شركة مصرية عريقة تأسست عام 1930! 🏛️ أسسها الدكتور منير رياض أرمانيوس بناءً على إرث والده الدكتور رياض أرمانيوس الذي أسس صيدلية في 1917. عندنا خبرة 90+ سنة في مستحضرات التجميل والعناية بالبشرة والشعر. عايز تعرف أكتر عن تاريخنا؟', 'intent': 'company_info', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-7', 'message': 'Tell me about Eva company', 'response': 'Eva Cosmetics is an established Egyptian company founded in 1930! 🏛️ Founded by Dr. Mounir Riad Armanious, building on his father Dr. Riad Armanious\'s pharmacy from 1917. We have 90+ years of experience in cosmetics and skincare. Want to know more about our history?', 'intent': 'company_info', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-8', 'message': 'إيفا شركة إيه؟', 'response': 'إيفا كوزمتكس شركة مصرية رائدة في مستحضرات التجميل والعناية بالبشرة والشعر! 💄 عندنا منتجات للرجال والنساء والأطفال، ومنتجات طبية معتمدة من أطباء الجلدية. عايز تعرف عن منتجات معينة؟', 'intent': 'company_info', 'sentiment': 'neutral', 'confidence': 0.90},
    
    # ========== مشاكل البشرة - حب الشباب ==========
    {'user_id': 'ext-9', 'message': 'عندي حب شباب شديد', 'response': 'حب الشباب الشديد يحتاج عناية خاصة! 🤗 أنصحك بالمنتجات التالية:\n\n💄 المنتجات الموصى بها:\n• غسول إيفا اللطيف للبشرة الدهنية (150ج) - مرتين يومياً\n• سيرم فيتامين C (350ج) - صباحاً\n• كريم علاج الحبوب (280ج) - مساءً\n\n🔄 الروتين:\nصباحاً: غسول → سيرم → مرطب خفيف → واقي شمس\nمساءً: غسول → علاج موضعي → مرطب مهدئ\n\n⚠️ نصائح مهمة:\n• لا تعصر الحبوب نهائياً\n• غير غطاء الوسادة يومياً\n• تجنب لمس الوجه\n• استشر طبيب جلدية إذا كان شديد\n\n💡 عايز نصائح إضافية؟', 'intent': 'severe_acne', 'sentiment': 'negative', 'confidence': 0.95},
    {'user_id': 'ext-10', 'message': 'I have severe acne', 'response': 'Severe acne needs special care! 🤗 I recommend:\n\n💄 Recommended Products:\n• Eva Gentle Cleanser (150 EGP) - twice daily\n• Vitamin C Serum (350 EGP) - morning\n• Acne Treatment Cream (280 EGP) - evening\n\n🔄 Routine:\nMorning: Cleanser → Serum → Light moisturizer → Sunscreen\nEvening: Cleanser → Spot treatment → Soothing moisturizer\n\n⚠️ Important Tips:\n• Never squeeze pimples\n• Change pillowcase daily\n• Avoid touching face\n• Consult dermatologist if severe\n\n💡 Want more tips?', 'intent': 'severe_acne', 'sentiment': 'negative', 'confidence': 0.95},
    {'user_id': 'ext-11', 'message': 'عندي حبوب في الظهر', 'response': 'حبوب الظهر مشكلة شائعة! 💪 الحل:\n\n💄 المنتجات:\n• غسول إيفا اللطيف (150ج) - استخدمه في الاستحمام\n• مقشر إيفا اللطيف (180ج) - مرتين أسبوعياً\n\n🔄 الروتين:\n• استحمام يومي بالغسول\n• مقشر مرتين أسبوعياً\n• مرطب خفيف بعد الاستحمام\n• ارتداء ملابس قطنية\n\n💡 نصائح:\n• تجنب الملابس الضيقة\n• غير الملابس بعد التعرق\n• استخدم منشفة نظيفة\n\nعايز تفاصيل أكتر؟', 'intent': 'back_acne', 'sentiment': 'negative', 'confidence': 0.90},
    
    # ========== البشرة الجافة ==========
    {'user_id': 'ext-12', 'message': 'بشرتي جافة ومتشققة', 'response': 'البشرة الجافة والمتشققة تحتاج ترطيب مكثف! 💧\n\n💄 المنتجات الموصى بها:\n• مرطب إيفا المائي (220ج) - مرتين يومياً\n• سيرم الترطيب المكثف (320ج) - صباحاً ومساءً\n• مقشر لطيف (180ج) - مرة أسبوعياً\n\n🔄 الروتين:\nصباحاً: غسول لطيف → سيرم → مرطب غني → واقي شمس\nمساءً: زيت منظف → سيرم → كريم ليلي مكثف\n\n💡 نصائح مهمة:\n• استخدم الماء الفاتر (ليس ساخن)\n• رطب فوراً بعد الغسيل\n• استخدم مرطب الجو\n• اشرب الماء بانتظام\n• تجنب المنتجات القاسية\n\nعايز تفاصيل أكتر؟', 'intent': 'very_dry_skin', 'sentiment': 'negative', 'confidence': 0.95},
    {'user_id': 'ext-13', 'message': 'My skin is very dry and flaky', 'response': 'Very dry and flaky skin needs intensive hydration! 💧\n\n💄 Recommended Products:\n• Eva Hydrating Moisturizer (220 EGP) - twice daily\n• Intensive Hydrating Serum (320 EGP) - morning & evening\n• Gentle Exfoliator (180 EGP) - once weekly\n\n🔄 Routine:\nMorning: Gentle cleanser → Serum → Rich moisturizer → Sunscreen\nEvening: Oil cleanser → Serum → Intensive night cream\n\n💡 Important Tips:\n• Use lukewarm water (not hot)\n• Moisturize immediately after washing\n• Use humidifier\n• Drink water regularly\n• Avoid harsh products\n\nWant more details?', 'intent': 'very_dry_skin', 'sentiment': 'negative', 'confidence': 0.95},
    
    # ========== البشرة الدهنية ==========
    {'user_id': 'ext-14', 'message': 'بشرتي دهنية جداً وبراقه', 'response': 'البشرة الدهنية جداً تحتاج تنظيف عميق! ✨\n\n💄 المنتجات:\n• غسول إيفا اللطيف (150ج) - مرتين يومياً\n• واقي الشمس SPF 50+ (280ج) - تركيبة خفيفة\n• مقشر (180ج) - مرتين أسبوعياً\n\n🔄 الروتين:\nصباحاً: غسول → سيرم خفيف → واقي شمس\nمساءً: غسول → مقشر (مرتين أسبوعياً) → مرطب خفيف\n\n💡 نصائح:\n• لا تغسلي أكثر من مرتين يومياً\n• استخدمي منتجات خفيفة غير دهنية\n• واقي الشمس ضروري\n• تجنبي المنتجات الثقيلة\n\nعايز تفاصيل أكتر؟', 'intent': 'very_oily_skin', 'sentiment': 'neutral', 'confidence': 0.90},
    
    # ========== البشرة الحساسة ==========
    {'user_id': 'ext-15', 'message': 'بشرتي حساسة ومتهيجة دائماً', 'response': 'البشرة الحساسة جداً تحتاج عناية خاصة! 🧡\n\n💄 المنتجات الآمنة:\n• غسول إيفا اللطيف (150ج) - خالي من العطور\n• مرطب إيفا المائي (220ج) - مهدئ\n• واقي شمس معدني (280ج) - للبشرة الحساسة\n\n🔄 الروتين:\nصباحاً: غسول لطيف → مرطب → واقي شمس\nمساءً: غسول لطيف → مرطب مهدئ\n\n⚠️ نصائح مهمة:\n• تجنبي المنتجات القاسية\n• اختبري على منطقة صغيرة أولاً\n• استخدمي منتجات خالية من العطور\n• تجنبي المقشرات القوية\n• استشيري طبيب إذا استمر التهيج\n\nعايز تفاصيل أكتر؟', 'intent': 'very_sensitive_skin', 'sentiment': 'negative', 'confidence': 0.95},
    
    # ========== البقع الداكنة ==========
    {'user_id': 'ext-16', 'message': 'عندي بقع داكنة كتيرة في وجهي', 'response': 'البقع الداكنة الكثيرة تحتاج علاج مكثف! 🌟\n\n💄 المنتجات:\n• سيرم فيتامين C (350ج) - صباحاً يومياً\n• مقشر إيفا اللطيف (180ج) - مرتين أسبوعياً\n• واقي شمس SPF 50+ (280ج) - مهم جداً!\n\n🔄 الروتين:\nصباحاً: غسول → سيرم فيتامين C → مرطب → واقي شمس (ضروري!)\nمساءً: غسول → مقشر (مرتين أسبوعياً) → مرطب\n\n⏱️ النتائج:\n• تظهر خلال 6-8 أسابيع\n• استخدام منتظم مهم جداً\n• واقي الشمس يمنع ظهور بقع جديدة\n\n💡 نصائح:\n• تجنبي التعرض للشمس المباشرة\n• استخدمي واقي شمس حتى في الشتاء\n• الصبر مهم - النتائج تحتاج وقت\n\nعايز تفاصيل أكتر؟', 'intent': 'many_dark_spots', 'sentiment': 'negative', 'confidence': 0.90},
    
    # ========== التجاعيد ==========
    {'user_id': 'ext-17', 'message': 'عندي تجاعيد عميقة', 'response': 'التجاعيد العميقة تحتاج علاج مكثف! 💪\n\n💄 المنتجات:\n• سيرم فيتامين C (350ج) - يحفز الكولاجين\n• مرطب إيفا المائي (220ج) - حمض الهيالورونيك\n• كريم ليلي مكثف (320ج) - إصلاح ليلي\n\n🔄 الروتين:\nصباحاً: غسول → سيرم فيتامين C → مرطب → واقي شمس (مهم جداً!)\nمساءً: غسول → سيرم → كريم ليلي مكثف\n\n💡 نصائح مهمة:\n• واقي الشمس أهم منتج ضد التجاعيد\n• النوم الكافي (7-8 ساعات)\n• شرب الماء بانتظام\n• تجنب التدخين\n• نظام غذائي صحي\n\n⏱️ النتائج: تظهر خلال 8-12 أسبوع\n\nعايز تفاصيل أكتر؟', 'intent': 'deep_wrinkles', 'sentiment': 'negative', 'confidence': 0.90},
    
    # ========== الشعر التالف ==========
    {'user_id': 'ext-18', 'message': 'شعري تالف جداً ومتقصف', 'response': 'الشعر التالف جداً يحتاج إصلاح مكثف! 💇‍♀️\n\n💄 المنتجات:\n• ماسك إيفا هير كلينك (200ج) - إصلاح مكثف\n• شامبو ألو إيفا (120ج) - ترطيب عميق\n• بلسم إيفا (150ج) - حماية من التلف\n\n🔄 الروتين:\n• شامبو وبلسم في كل غسلة\n• ماسك مرتين أسبوعياً (اتركيه 20 دقيقة)\n• قص الأطراف كل 6-8 أسابيع\n• تجنب الحرارة الزائدة\n\n💡 نصائح:\n• استخدمي مشط واسع الأسنان\n• جففي بالمنشفة برفق\n• تجنبي الصبغة الكيميائية القاسية\n• استخدمي حماية من الحرارة\n\n⏱️ النتائج: تظهر خلال 4-6 أسابيع\n\nعايز تفاصيل أكتر؟', 'intent': 'very_damaged_hair', 'sentiment': 'negative', 'confidence': 0.90},
    {'user_id': 'ext-19', 'message': 'My hair is very damaged from coloring', 'response': 'Hair damaged from coloring needs intensive repair! 💇‍♀️\n\n💄 Products:\n• Eva Hair Clinic Mask (200 EGP) - intensive repair\n• Aloe Eva Shampoo (120 EGP) - deep hydration\n• Eva Conditioner (150 EGP) - damage protection\n\n🔄 Routine:\n• Shampoo and conditioner every wash\n• Mask twice weekly (leave 20 minutes)\n• Trim ends every 6-8 weeks\n• Avoid excessive heat\n\n💡 Tips:\n• Use wide-tooth comb\n• Dry gently with towel\n• Avoid harsh chemical dyes\n• Use heat protection\n\n⏱️ Results: Appear in 4-6 weeks\n\nWant more details?', 'intent': 'colored_damaged_hair', 'sentiment': 'negative', 'confidence': 0.90},
    
    # ========== أسئلة المنتجات ==========
    {'user_id': 'ext-20', 'message': 'إيه أفضل منتج للبشرة الدهنية؟', 'response': 'للبشرة الدهنية، أنصحك بـ:\n\n🏆 المنتج الأول: غسول إيفا اللطيف (150ج)\n• يحتوي على حمض الساليسيليك 2%\n• ينظف المسام بعمق\n• يقلل الزيوت الزائدة\n• مناسب للاستخدام اليومي\n\n🏆 المنتج الثاني: واقي الشمس SPF 50+ (280ج)\n• تركيبة خفيفة غير دهنية\n• لا يسد المسام\n• مقاوم للماء\n\n💡 نصيحة: استخدمي الغسول مرتين يومياً والواقي كل صباح!\n\nعايز تعرف عن منتجات تانية؟', 'intent': 'best_product_oily', 'sentiment': 'neutral', 'confidence': 0.95},
    {'user_id': 'ext-21', 'message': 'What\'s the best product for dry skin?', 'response': 'For dry skin, I recommend:\n\n🏆 Top Product: Eva Hydrating Moisturizer (220 EGP)\n• Contains Hyaluronic Acid\n• Retains moisture for 48 hours\n• 5% Niacinamide strengthens barrier\n• Ceramides prevent water loss\n\n🏆 Second: Gentle Exfoliator (180 EGP)\n• Natural fruit acids\n• Removes dead skin\n• Deeply moisturizes\n\n💡 Tip: Use moisturizer twice daily and exfoliator once weekly!\n\nWant to know about other products?', 'intent': 'best_product_dry', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== الأسعار ==========
    {'user_id': 'ext-22', 'message': 'كام سعر السيرم؟', 'response': 'سيرم فيتامين C المضاد للأكسدة - 350 جنيه 💰\n\n**الفوائد:**\n• يفتح البقع الداكنة\n• يحارب الجذور الحرة\n• يعزز إنتاج الكولاجين\n• يوحد لون البشرة\n\n**الحجم:** 30 مل\n**الاستخدام:** صباحاً يومياً\n**النتائج:** تظهر خلال 4-6 أسابيع\n\n💡 عايز تعرف عن منتجات تانية أو عروض خاصة؟', 'intent': 'serum_price', 'sentiment': 'neutral', 'confidence': 0.95},
    {'user_id': 'ext-23', 'message': 'How much is the moisturizer?', 'response': 'Eva Hydrating Moisturizer - 220 EGP 💰\n\n**Benefits:**\n• Hyaluronic Acid for deep hydration\n• 48-hour moisture retention\n• 5% Niacinamide\n• Ceramides for barrier protection\n\n**Size:** 50 ml\n**Usage:** Twice daily\n**Results:** Immediate hydration\n\n💡 Want to know about other products or special offers?', 'intent': 'moisturizer_price', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== طريقة الاستخدام ==========
    {'user_id': 'ext-24', 'message': 'إزاي أستخدم السيرم صح؟', 'response': 'طريقة استخدام السيرم الصحيحة! 💧\n\n**الخطوات:**\n1. اغسلي وجهك بالغسول أولاً\n2. جففي البشرة برفق\n3. ضعي 2-3 قطرات من السيرم\n4. دلكي برفق على الوجه والرقبة\n5. انتظري 2-3 دقائق\n6. ضعي المرطب\n7. اتبعي بواقي الشمس (صباحاً)\n\n**متى تستخدمي:**\n• صباحاً: بعد الغسيل، قبل المرطب\n• مساءً: بعد الغسيل، قبل المرطب\n\n**نصائح:**\n• ابدأي بكل يومين ثم يومياً\n• استخدمي واقي شمس بعده (صباحاً)\n• خزني في مكان بارد ومظلم\n\n💡 عايز تفاصيل أكتر عن منتج معين؟', 'intent': 'how_to_use_serum', 'sentiment': 'neutral', 'confidence': 0.95},
    {'user_id': 'ext-25', 'message': 'How do I use the cleanser properly?', 'response': 'Proper cleanser usage! 🧼\n\n**Steps:**\n1. Wet your face with lukewarm water\n2. Apply cleanser to hands\n3. Lather and massage gently\n4. Leave for 30 seconds\n5. Rinse thoroughly with water\n6. Pat dry with clean towel\n7. Follow with moisturizer\n\n**When to use:**\n• Morning: Start of routine\n• Evening: Remove makeup/dirt\n\n**Tips:**\n• Use twice daily maximum\n• Don\'t over-wash\n• Use lukewarm water (not hot)\n• Pat dry (don\'t rub)\n\n💡 Want details about other products?', 'intent': 'how_to_use_cleanser', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== التوافق بين المنتجات ==========
    {'user_id': 'ext-26', 'message': 'ممكن أستخدم فيتامين سي مع الريتينول؟', 'response': 'سؤال مهم! ⚠️\n\n**القاعدة العامة:**\n• لا تستخدميهم في نفس الوقت\n• ممكن يسببوا تهيج عند الجمع\n\n**الطريقة الصحيحة:**\n• **صباحاً:** سيرم فيتامين C + واقي شمس\n• **مساءً:** الريتينول (إذا كنتي تستخدميه)\n\n**ليه؟**\n• فيتامين C يعمل أفضل صباحاً (يحمي من الشمس)\n• الريتينول يعمل أفضل مساءً (حساس للضوء)\n• الفصل بينهم يقلل خطر التهيج\n\n**بديل:**\n• استخدمي فيتامين C يومياً صباحاً\n• استخدمي الريتينول 2-3 مرات أسبوعياً مساءً\n\n💡 عايز روتين مخصص ليك؟', 'intent': 'vitamin_c_retinol', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== الروتين اليومي ==========
    {'user_id': 'ext-27', 'message': 'إيه روتين كامل للبشرة؟', 'response': 'روتين كامل للعناية بالبشرة! ✨\n\n**صباحاً (Morning Routine):**\n1. غسول إيفا اللطيف\n2. سيرم فيتامين C (اختياري)\n3. مرطب إيفا المائي\n4. واقي شمس SPF 50+ (مهم جداً!)\n\n**مساءً (Evening Routine):**\n1. غسول إيفا اللطيف (أو زيت منظف)\n2. سيرم (اختياري)\n3. مرطب أو كريم ليلي\n\n**أسبوعياً (Weekly):**\n• مقشر إيفا اللطيف - مرة أو مرتين\n• ماسك للبشرة (اختياري)\n\n**نصائح مهمة:**\n• واقي الشمس أهم خطوة!\n• استخدمي منتجات مناسبة لنوع بشرتك\n• الصبر مهم - النتائج تحتاج وقت\n• النوم الكافي مهم جداً\n\n💡 عايز روتين مخصص لنوع بشرتك؟', 'intent': 'complete_routine', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== أسئلة طبية ==========
    {'user_id': 'ext-28', 'message': 'منتجات إيفا آمنة للحامل؟', 'response': 'معظم منتجات إيفا آمنة للحامل! ✅\n\n**المنتجات الآمنة تماماً:**\n• غسول إيفا اللطيف\n• مرطب إيفا المائي\n• مقشر إيفا اللطيف\n• شامبو ألو إيفا\n• بلسم إيفا\n\n**يحتاج استشارة طبية:**\n• واقي الشمس SPF 50+ (استشيري طبيبك)\n• أي منتج يحتوي على ريتينول\n• منتجات علاجية قوية\n\n**نصائح للحامل:**\n• استخدمي منتجات لطيفة\n• تجنبي المنتجات القوية\n• استشيري طبيبك دائماً\n• اختبري على منطقة صغيرة أولاً\n\n⚠️ نصيحة: استشيري طبيبك قبل استخدام أي منتج جديد أثناء الحمل!\n\n💡 عايز توصيات محددة للحمل؟', 'intent': 'pregnancy_safe', 'sentiment': 'neutral', 'confidence': 0.90},
    
    # ========== العناية بالشعر ==========
    {'user_id': 'ext-29', 'message': 'شعري جاف ومحتاج ترطيب', 'response': 'الشعر الجاف يحتاج ترطيب مكثف! 💧\n\n💄 المنتجات:\n• شامبو ألو إيفا المرطب (120ج)\n• بلسم إيفا للشعر الجاف (150ج)\n• ماسك إيفا هير كلينك (200ج)\n\n🔄 الروتين:\n• شامبو وبلسم في كل غسلة\n• ماسك مرة أو مرتين أسبوعياً\n• تجنب الحرارة الزائدة\n• قص الأطراف بانتظام\n\n💡 نصائح:\n• استخدمي ماء فاتر (ليس ساخن)\n• جففي بالمنشفة برفق\n• استخدمي حماية من الحرارة\n• تجنبي الصبغة القاسية\n\nعايز تفاصيل أكتر؟', 'intent': 'dry_hair_hydration', 'sentiment': 'neutral', 'confidence': 0.90},
    
    # ========== أسئلة عامة ==========
    {'user_id': 'ext-30', 'message': 'إيه الفرق بين الشامبو والبلسم والماسك؟', 'response': 'سؤال مهم! 🤔\n\n**الشامبو (Shampoo):**\n• ينظف الشعر وفروة الرأس\n• يزيل الأوساخ والزيوت\n• يستخدم أولاً\n• مثال: شامبو ألو إيفا (120ج)\n\n**البلسم (Conditioner):**\n• يرطب الشعر بعد الغسيل\n• يسهل التمشيط\n• يحمي من التلف\n• يستخدم بعد الشامبو\n• مثال: بلسم إيفا (150ج)\n\n**الماسك (Mask):**\n• إصلاح مكثف للشعر التالف\n• ترطيب عميق\n• يستخدم مرة أو مرتين أسبوعياً\n• يترك 15-20 دقيقة\n• مثال: ماسك إيفا هير كلينك (200ج)\n\n**الترتيب:**\n1. شامبو (ينظف)\n2. بلسم (يرطب)\n3. ماسك (إصلاح - أسبوعياً)\n\n💡 عايز تفاصيل أكتر عن منتج معين؟', 'intent': 'shampoo_conditioner_mask', 'sentiment': 'neutral', 'confidence': 0.95},
    
    # ========== المزيد من الأسئلة المتنوعة ==========
    {'user_id': 'ext-31', 'message': 'ممكن توصية روتين للبشرة المختلطة؟', 'response': 'البشرة المختلطة تحتاج روتين متوازن! ⚖️\n\n**المناطق الدهنية (T-zone):**\n• غسول للبشرة الدهنية\n• مرطب خفيف\n\n**المناطق الجافة (الخدود):**\n• غسول لطيف\n• مرطب غني\n\n**المنتجات المناسبة:**\n• غسول إيفا اللطيف (150ج) - للكل\n• مرطب إيفا المائي (220ج) - متوازن\n• واقي شمس SPF 50+ (280ج)\n\n**الروتين:**\nصباحاً: غسول → مرطب → واقي شمس\nمساءً: غسول → مرطب\nأسبوعياً: مقشر مرة واحدة\n\n💡 نصيحة: استخدمي منتجات متوازنة تناسب المنطقتين!\n\nعايز تفاصيل أكتر؟', 'intent': 'combination_skin_routine', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-32', 'message': 'How often should I wash my face?', 'response': 'Great question! 🧼\n\n**General Rule:**\n• **Oily Skin:** Twice daily (morning & evening)\n• **Dry Skin:** Once or twice daily\n• **Normal Skin:** Twice daily\n• **Sensitive Skin:** Once daily (evening)\n\n**Best Times:**\n• Morning: Remove overnight oil\n• Evening: Remove makeup, dirt, pollution\n\n**Don\'t Over-wash:**\n• Washing more than twice can dry skin\n• Can cause irritation\n• Can increase oil production\n\n**Tips:**\n• Use gentle cleanser\n• Use lukewarm water\n• Pat dry (don\'t rub)\n• Moisturize immediately after\n\n💡 Want product recommendations?', 'intent': 'washing_frequency', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-33', 'message': 'إيه أهمية واقي الشمس؟', 'response': 'واقي الشمس أهم منتج للعناية بالبشرة! ☀️\n\n**الفائدة:**\n• يحمي من أشعة UV الضارة\n• يمنع البقع الداكنة\n• يمنع التجاعيد\n• يقلل خطر سرطان الجلد\n• يحافظ على نضارة البشرة\n\n**متى تستخدمي:**\n• كل صباح (حتى في الشتاء!)\n• قبل الخروج بنصف ساعة\n• أعيدي كل ساعتين إذا كنتي خارج\n\n**SPF 50+:**\n• يحجب 98% من أشعة UVB\n• أفضل حماية للاستخدام اليومي\n\n**منتج إيفا:**\n• واقي الشمس SPF 50+ (280ج)\n• تركيبة خفيفة غير دهنية\n• مقاوم للماء\n\n💡 نصيحة: واقي الشمس أهم من أي منتج تاني!\n\nعايز تفاصيل أكتر؟', 'intent': 'sunscreen_importance', 'sentiment': 'neutral', 'confidence': 0.95},
    {'user_id': 'ext-34', 'message': 'عندي بشرة عادية، إيه محتاج؟', 'response': 'البشرة العادية محظوظة! لكن تحتاج عناية للحفاظ عليها! 🌟\n\n**المنتجات الأساسية:**\n• غسول إيفا اللطيف (150ج) - للتنظيف\n• مرطب إيفا المائي (220ج) - للترطيب\n• واقي شمس SPF 50+ (280ج) - للحماية\n\n**الروتين البسيط:**\nصباحاً: غسول → مرطب → واقي شمس\nمساءً: غسول → مرطب\n\n**اختياري:**\n• سيرم فيتامين C (350ج) - للإشراقة\n• مقشر (180ج) - مرة أسبوعياً\n\n**نصائح:**\n• حافظي على الروتين البسيط\n• واقي الشمس مهم حتى للبشرة العادية\n• النوم الكافي مهم\n• نظام غذائي صحي\n\n💡 عايز تفاصيل أكتر عن منتج معين؟', 'intent': 'normal_skin_care', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-35', 'message': 'What ingredients should I avoid?', 'response': 'Important question! ⚠️\n\n**Ingredients to Avoid (if sensitive):**\n• **Alcohol:** Can dry skin\n• **Fragrance:** Can irritate sensitive skin\n• **Sulfates:** Can be harsh\n• **Parabens:** Some prefer to avoid\n\n**Eva Products:**\n• Many are fragrance-free\n• Gentle formulations\n• Dermatologist-approved\n• Suitable for sensitive skin\n\n**Always:**\n• Patch test new products\n• Read ingredient lists\n• Consult dermatologist if concerned\n• Listen to your skin\n\n**Eva\'s Approach:**\n• Natural ingredients when possible\n• Safe formulations\n• Tested and approved\n\n💡 Want product recommendations for sensitive skin?', 'intent': 'ingredients_to_avoid', 'sentiment': 'neutral', 'confidence': 0.85},
    
    # ========== المزيد من الأسئلة المتنوعة ==========
    {'user_id': 'ext-36', 'message': 'إيه أفضل وقت لاستخدام السيرم؟', 'response': 'أفضل وقت لاستخدام السيرم! ⏰\n\n**سيرم فيتامين C:**\n• **صباحاً:** أفضل وقت (يحمي من الشمس)\n• بعد الغسيل مباشرة\n• قبل المرطب\n• دائماً اتبعي بواقي شمس\n\n**سيرم الريتينول (إن وجد):**\n• **مساءً فقط:** حساس للضوء\n• بعد الغسيل\n• قبل المرطب\n\n**نصائح:**\n• استخدمي السيرم على بشرة نظيفة\n• انتظري 2-3 دقائق قبل المرطب\n• ابدأي بكل يومين ثم يومياً\n• خزني في مكان بارد ومظلم\n\n💡 عايز تفاصيل أكتر عن سيرم معين؟', 'intent': 'serum_timing', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-37', 'message': 'How long until I see results?', 'response': 'Great question about timing! ⏱️\n\n**General Timeline:**\n• **Immediate:** Hydration, smoothness\n• **2-4 weeks:** Texture improvement\n• **4-6 weeks:** Visible results (acne, dark spots)\n• **8-12 weeks:** Significant improvement (wrinkles, pigmentation)\n\n**Product-Specific:**\n• **Cleanser:** Immediate clean feeling\n• **Moisturizer:** Instant hydration\n• **Serum:** 4-6 weeks for visible results\n• **Exfoliator:** 2-4 weeks for smoother skin\n\n**Important:**\n• Consistency is key!\n• Use products regularly\n• Don\'t give up too soon\n• Results vary by person\n\n💡 Want product-specific timelines?', 'intent': 'results_timeline', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-38', 'message': 'عندي بشرة دهنية في الصيف وجافة في الشتاء', 'response': 'البشرة المتغيرة حسب الفصل تحتاج روتين مرن! 🌦️\n\n**الصيف (دهنية):**\n• غسول للبشرة الدهنية (150ج)\n• مرطب خفيف\n• واقي شمس SPF 50+ (280ج) - مهم جداً!\n• مقشر مرتين أسبوعياً\n\n**الشتاء (جافة):**\n• غسول لطيف\n• مرطب غني (220ج)\n• واقي شمس (مهم حتى في الشتاء!)\n• مقشر مرة أسبوعياً\n\n**نصائح:**\n• استمعي لبشرتك\n• غيري الروتين حسب الحاجة\n• واقي الشمس مهم في كل الفصول\n• الترطيب مهم في الشتاء\n\n💡 عايز روتين مخصص لكل فصل؟', 'intent': 'seasonal_skin', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-39', 'message': 'Can I use multiple serums?', 'response': 'Yes, but carefully! ⚠️\n\n**General Rule:**\n• Don\'t use too many at once\n• Maximum 2 serums per routine\n• Separate by time (morning/evening)\n\n**Good Combinations:**\n• **Morning:** Vitamin C + Hyaluronic Acid\n• **Evening:** Retinol + Niacinamide\n\n**Don\'t Combine:**\n• Vitamin C + Retinol (same time)\n• Too many active ingredients\n\n**Best Practice:**\n• Morning: Vitamin C serum\n• Evening: Retinol or other treatment\n• Always use moisturizer after\n• Always use sunscreen (morning)\n\n💡 Want a personalized serum routine?', 'intent': 'multiple_serums', 'sentiment': 'neutral', 'confidence': 0.85},
    {'user_id': 'ext-40', 'message': 'إيه الفرق بين المرطب والكريم؟', 'response': 'سؤال مهم! 🤔\n\n**المرطب (Moisturizer):**\n• أخف في القوام\n• للاستخدام اليومي\n• مناسب للبشرة الدهنية\n• يمتص بسرعة\n• مثال: مرطب إيفا المائي (220ج)\n\n**الكريم (Cream):**\n• أثقل في القوام\n• للبشرة الجافة\n• ترطيب مكثف\n• للاستخدام الليلي\n• مثال: كريم ليلي مكثف (320ج)\n\n**متى تستخدمي:**\n• **المرطب:** صباحاً، للبشرة الدهنية/العادية\n• **الكريم:** مساءً، للبشرة الجافة، في الشتاء\n\n**نصيحة:**\n• البشرة الدهنية: مرطب خفيف\n• البشرة الجافة: كريم غني\n• البشرة المختلطة: مرطب متوازن\n\n💡 عايز توصية حسب نوع بشرتك؟', 'intent': 'moisturizer_vs_cream', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-41', 'message': 'What is the difference between toner and serum?', 'response': 'Great question! 🤔\n\n**Toner:**\n• Liquid consistency\n• Used after cleansing\n• Prepares skin for other products\n• Can balance pH\n• Lightweight\n\n**Serum:**\n• More concentrated\n• Active ingredients\n• Used after toner (if used)\n• Targets specific concerns\n• More potent\n\n**Order of Use:**\n1. Cleanser\n2. Toner (optional)\n3. Serum\n4. Moisturizer\n5. Sunscreen (morning)\n\n**Eva Products:**\n• We focus on cleanser → serum → moisturizer\n• Simple, effective routine\n\n💡 Want product recommendations?', 'intent': 'toner_vs_serum', 'sentiment': 'neutral', 'confidence': 0.85},
    {'user_id': 'ext-42', 'message': 'عندي حساسية من منتج، أعمل إيه؟', 'response': 'إذا حدثت حساسية، اتصلي فوراً! 🚨\n\n**خطوات فورية:**\n1. توقفي عن استخدام المنتج فوراً\n2. اغسلي وجهك بماء بارد\n3. استخدمي مرطب لطيف فقط\n4. تجنبي المنتجات الأخرى\n\n**إذا كانت الحساسية شديدة:**\n• استشيري طبيب فوراً\n• اتصلي بخدمة عملاء إيفا: 17125\n• أو shop@eva-cosmetics.com\n\n**للوقاية:**\n• اختبري المنتج على منطقة صغيرة أولاً\n• ابدأي بكمية قليلة\n• راقبي رد فعل بشرتك\n\n**منتجات إيفا:**\n• معتمدة من أطباء الجلدية\n• آمنة للبشرة الحساسة\n• لكن كل بشرة مختلفة\n\n⚠️ نصيحة: دائماً اختبري على منطقة صغيرة أولاً!\n\n💡 عايز توصيات لمنتجات لطيفة؟', 'intent': 'allergy_reaction', 'sentiment': 'negative', 'confidence': 0.95},
    {'user_id': 'ext-43', 'message': 'إيه أفضل منتج للرجال؟', 'response': 'منتجات إيفا مناسبة للرجال والنساء! 👨\n\n**المنتجات الموصى بها للرجال:**\n• غسول إيفا اللطيف (150ج) - للوجه\n• مرطب إيفا المائي (220ج) - خفيف وغير دهني\n• واقي شمس SPF 50+ (280ج) - مهم جداً!\n\n**روتين بسيط للرجال:**\nصباحاً: غسول → مرطب → واقي شمس\nمساءً: غسول → مرطب\n\n**للشعر:**\n• شامبو ألو إيفا (120ج)\n• بلسم إيفا (150ج)\n\n**نصائح:**\n• الروتين البسيط أفضل\n• واقي الشمس مهم للرجال كمان\n• الترطيب مهم بعد الحلاقة\n\n💡 عايز روتين مخصص للرجال؟', 'intent': 'men_skincare', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-44', 'message': 'How do I know my skin type?', 'response': 'Great question! Here\'s how to identify: 🔍\n\n**Oily Skin:**\n• Shiny, especially T-zone\n• Large pores\n• Prone to acne\n• Makeup doesn\'t last\n\n**Dry Skin:**\n• Feels tight\n• Flaky or rough\n• Small pores\n• Fine lines visible\n\n**Combination Skin:**\n• Oily T-zone\n• Dry cheeks\n• Mixed characteristics\n\n**Normal Skin:**\n• Balanced\n• Few imperfections\n• Not too oily or dry\n• Smooth texture\n\n**Sensitive Skin:**\n• Easily irritated\n• Redness\n• Reacts to products\n• Itching or burning\n\n**Test:**\n• Wash face, wait 30 minutes\n• Check how it feels\n• Observe oiliness/dryness\n\n💡 Want product recommendations for your skin type?', 'intent': 'identify_skin_type', 'sentiment': 'neutral', 'confidence': 0.90},
    {'user_id': 'ext-45', 'message': 'إزاي أعرف نوع بشرتي؟', 'response': 'سؤال مهم! إزاي تعرفي نوع بشرتك: 🔍\n\n**البشرة الدهنية:**\n• لامعة خاصة في منطقة T\n• مسام كبيرة\n• معرضة للحبوب\n• المكياج مايستمرش\n\n**البشرة الجافة:**\n• محسوسة ضيقة\n• متقشرة أو خشنة\n• مسام صغيرة\n• خطوط دقيقة واضحة\n\n**البشرة المختلطة:**\n• دهنية في منطقة T\n• جافة في الخدود\n• خصائص مختلطة\n\n**البشرة العادية:**\n• متوازنة\n• قليل من العيوب\n• مش دهنية ولا جافة\n• ملمس ناعم\n\n**البشرة الحساسة:**\n• سهلة التهيج\n• احمرار\n• تتفاعل مع المنتجات\n• حكة أو حرقان\n\n**اختبار:**\n• اغسلي وجهك، انتظري 30 دقيقة\n• شوفي إزاي محسوسة\n• لاحظي الدهنية/الجفاف\n\n💡 عايز توصيات منتجات حسب نوع بشرتك؟', 'intent': 'identify_skin_type_ar', 'sentiment': 'neutral', 'confidence': 0.90},
]

def add_extensive_training_data():
    """إضافة بيانات التدريب الشاملة"""
    logger.info("="*70)
    logger.info("🚀 Starting Extensive Training Data Addition")
    logger.info("="*70)
    
    added_count = 0
    
    try:
        # Add conversations
        logger.info(f"\n[1/1] Adding {len(EXTENSIVE_CONVERSATIONS)} conversations...")
        for conv in EXTENSIVE_CONVERSATIONS:
            try:
                save_conversation(
                    user_id=conv['user_id'],
                    message=conv['message'],
                    response=conv['response'],
                    intent=conv['intent'],
                    sentiment=conv['sentiment'],
                    confidence=conv['confidence']
                )
                added_count += 1
                if added_count % 10 == 0:
                    logger.info(f"✅ Added {added_count} conversations...")
            except Exception as e:
                logger.error(f"❌ Error adding conversation {conv['user_id']}: {e}")
        
        logger.info("\n" + "="*70)
        logger.info(f"✅ Successfully added {added_count} training conversations!")
        logger.info("="*70)
        
    except Exception as e:
        logger.error(f"❌ Error in add_extensive_training_data: {e}")

if __name__ == '__main__':
    add_extensive_training_data()

